### ISSUE TITLE
Port Definition, Formula, Log and Sleep tasks from HQCMeas to Ecpy 

### ISSUE THREAD

**Issue by MatthieuDartiailh** [Ecpy/ecpy#5]

**Comment by MatthieuDartiailh** [comment]
@leghtas This may be a good starting point for you to start contributing. You should read the documentation linked to tasks, hopefully it should make things quite smooth.

**Comment by PhilipVinc** [comment]
@MatthieuDartiailh since we will be using a Dict for Formula/Definition task to store the various items, what is your idea for the key to be used in the database to store the various values? I guess it would make sense to store them as "Taskname_Keyname" (as we have only one dictionary in those tasks, and therefore we automatically avoid duplicate keys).

**Comment by MatthieuDartiailh** [comment]
Yes that is exactly what I was doing in HQCMeas.

**Comment by PhilipVinc** [comment]
Here is my code for the formula task that does not work well with the Database:
https://github.com/PhilipVinc/ecpy/tree/DefinitionFormula-dev
